### ISSUE TITLE
Some errors with latest versión

### ISSUE THREAD

**Issue by Zoiter7** [marcelo-mason/SimpleClans#417] opened 2017-03-19 22:17 UTC
Since version 2.6.0 in spigot 1.8.8 the database (SQLITE and MySql) don't works propertly and also the perms of leader.

**Comment by RoinujNosde** [comment] 2017-07-29 20:42
Related to #431.
http://104.236.246.108:8080/job/SimpleClans/lastStableBuild/artifact/target/SimpleClans.jar
Try this one.

**Comment by Zoiter7** [comment] 2017-07-29 22:02
Thanks. I will test it.

**Comment by Zoiter7** [comment] 2017-08-21 11:33
Now the problem with the database not exist, but the problems with the leader permissions continues
Is the same problem of this issue: https://github.com/marcelo-mason/SimpleClans/issues/440

**Comment by RoinujNosde** [comment] 2017-08-21 11:35
Duplicate of #440

**Closed by RoinujNosde** 2017-08-21 11:35 UTC
Labels: Awaiting Answer
