### ISSUE TITLE
Leader permissions does not work??

### ISSUE THREAD

**Issue by carelli99** [marcelo-mason/SimpleClans#431] opened 2017-07-18 11:15 UTC
Hi, when i execute some leader command, such as "/clan disband" i get "You do not have leader permission", i put all nodes to the group:

- simpleclans.anyone.*
- simpleclans.member.*
- simpleclans.leader.*

Last version SimpleClans
Spigot 1.11

Any help??? Thank you

**Comment by RoinujNosde** [comment] 2017-07-29 15:44
What is your permissions plugin and its version?
What's Vault's version?

**Comment by RoinujNosde** [comment] 2017-08-07 01:40
Duplicate of #440

**Closed by RoinujNosde** 2017-08-07 01:40 UTC
Labels: Awaiting Answer
