### ISSUE TITLE
People can't join clans

### ISSUE THREAD

**Issue by gravestristen** [marcelo-mason/SimpleClans#314] opened 2015-07-20 01:01 UTC
People have been invited but whenever someone does /accept nothing happens

**Comment by erik1988** [comment] 2015-07-22 13:33
duplicate of #252 (and many others).

**Comment by gravestristen** [comment] 2015-07-24 16:39
Update: People who have not changed names cannot join clans either.

**Comment by RoinujNosde** [comment] 2017-07-30 12:17
Duplicate of #331

**Closed by RoinujNosde** 2017-07-30 12:17 UTC
Labels: Duplicate
