### ISSUE TITLE
 Error saving modified Clans and ClanPlayers:

### ISSUE THREAD

**Issue by megamineservidores** [marcelo-mason/SimpleClans#637] opened 2020-07-08 05:06 UTC
[02:05:19 ERROR]: [SimpleClans] Error saving modified Clans and ClanPlayers:
[02:05:19 WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'color_tag' at row 1
[02:05:19 WARN]:        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:1065)
[02:05:19 WARN]:        at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.saveModified(StorageManager.java:1143)
[02:05:19 WARN]:        at net.sacredlabyrinth.phaed.simpleclans.tasks.SaveDataTask.run(SaveDataTask.java:26)
[02:05:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[02:05:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[02:05:19 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[02:05:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[02:05:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[02:05:19 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by RoinujNosde** [comment] 2020-07-08 10:11
Duplicate of #598 

The fix will be released in the next version.

**Closed by RoinujNosde** 2020-07-08 10:11 UTC
