### ISSUE TITLE
Clan /accept

### ISSUE THREAD

**Issue by ZielZane** [marcelo-mason/SimpleClans#332] opened 2015-11-04 03:05 UTC
On my server timgaming.com the /accept command does not go through when I'm invited, please look into it, thanks.

**Comment by i9hdkill** [comment] 2015-12-19 04:53
This happens when sc does not update the username after a player changed it.
Manually update the username in the database and reload the plugin to fix this issue for this player

**Comment by RoinujNosde** [comment] 2017-07-30 12:02
Still an issue?

**Comment by RoinujNosde** [comment] 2017-07-30 12:17
Duplicate of #331

**Closed by RoinujNosde** 2017-07-30 12:17 UTC
Labels: Duplicate
