### ISSUE TITLE
Space glitch when a role contains a spaces

### ISSUE THREAD

**Issue by Prototype5687** [marcelo-mason/SimpleClans#644] opened 2020-09-21 06:38 UTC
when a player made role contains a space the role cannot be deleted

**Comment by RoinujNosde** [comment] 2020-09-21 10:02
Active development is now on my fork: https://github.com/RoinujNosde/SimpleClans

Duplicate of RoinujNosde/SimpleClans#48

**Closed as completed by RoinujNosde** 2020-09-21 10:02 UTC
