### ISSUE TITLE
Does not work to invite players that have changed their name.

### ISSUE THREAD

**Issue by erik1988** [marcelo-mason/SimpleClans#252] opened 2015-04-05 09:02 UTC
Titile says it all. you can send a request, but they cant accept it. Also if you type /clan roster players would show with their old username. I have used "clan place" to handle this problem so far, but it would be great if it could be fixed.

**Comment by gravestristen** [comment] 2015-07-22 17:43
any time frame on when this will be fixed?

**Comment by RoinujNosde** [comment] 2017-07-30 12:15
Duplicate of #331

**Closed by RoinujNosde** 2017-07-30 12:15 UTC
Labels: Bug, Duplicate
