### ISSUE TITLE
Updating Config

### ISSUE THREAD

**Issue by TheMCMarine** [marcelo-mason/SimpleClans#421] opened 2017-05-31 17:30 UTC
When I update config, it all goes wrong. What is up with that? I will not change anyhting but the color, editing it completely normal. Please help

**Comment by RoinujNosde** [comment] 2017-07-29 20:31
What goes wrong?

**Comment by RoinujNosde** [comment] 2017-08-22 12:32
Duplicate of #413

**Closed by RoinujNosde** 2017-08-22 12:32 UTC
Labels: Awaiting Answer
