### ISSUE TITLE
Cuts some messages

### ISSUE THREAD

**Issue by BoomEaro** [marcelo-mason/SimpleClans#479] opened 2018-01-12 19:20 UTC
https://imgur.com/a/mVDTx
https://imgur.com/a/f5CcE
The plugin for some reason cuts off messages, as if there is a maximum limit, after which the word is not completely written. Also if you communicate with players through /. then some messages will also be reduced and transferred to the next line, which is not very convenient. (sorry for my english)

**Comment by RoinujNosde** [comment] 2018-01-12 21:33
@marcelo-mason 
This issue is actually a feature, is not it?
https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/ChatBlock.java#L352

**Comment by RoinujNosde** [comment] 2018-01-12 21:34
Duplicate of #392

**Closed** 2019-09-19 15:37 UTC
