### ISSUE TITLE
Clans /accept does not work

### ISSUE THREAD

**Issue by prodkid** [marcelo-mason/SimpleClans#300] opened 2015-06-20 21:44 UTC
When invited to a clan, /accept does not work. Also when you modify the plugin's config file in it's jar  to modify /accept to another command, still does not work.

**Comment by erik1988** [comment] 2015-06-21 09:05
I think this is the same as #252. It wont work because the players have changed their names. I hope this would get fixed soon. You can use "/clan place" (admin) until he fixes it.

**Comment by prodkid** [comment] 2015-08-05 18:47
Fixed in latest dev builds.

**Comment by erik1988** [comment] 2015-08-05 18:50
Unless there is a dev build that came out just this second, this problem is not fixed. :/

**Comment by prodkid** [comment] 2015-08-05 21:16
have you tried the builds here? http://repo.sacredlabyrinth.net:8080/job/SimpleClans/

**Comment by erik1988** [comment] 2015-08-05 22:15
Yes I have been using it since it came out, and yesterday was the last time I used the place command to put someone in a clan because accept did not work. so its not fixed. However it seems to work normally on some people, I think its caused by players changing name after they already have joined with another name.

**Comment by prodkid** [comment] 2015-08-06 01:46
Oh weird, i haven't experienced this but its currently running on a tested server

**Comment by RoinujNosde** [comment] 2017-07-30 12:16
Duplicate of #331

**Closed by RoinujNosde** 2017-07-30 12:16 UTC
Labels: Duplicate
